;(function($){
    $.fn.extend({
            'nav':function(){
                $(this).find('.nav').css({
                    'list-style':'none',
                    'width':'120px',
                    'color':'orange',
                    'margin':0,
                    'padding':0,
                    'display':'none'
                });
                $(this).find('.nav').parent().hover(function(){
                    $(this).find('.nav').slideDown();
                },function(){
                    $(this).find('.nav').stop().slideUp();
                })
            }
        }
    )
})(jQuery);